---
name: Shellcheck test

on:
  push:
    branches:
      - '**'
      - '!trunk'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: shellcheck
        uses: ludeeus/action-shellcheck@master